DEFINE tab_space_table=ACT0_TAB
DEFINE tab_space_index=ACT0_IDX

PROMPT Creating TABLE RESERVATION_USAGE
CREATE TABLE CHEMINFRA.RESERVATION_USAGE (
    ID NUMBER(8,0) NOT NULL
		CONSTRAINT pk_reservation_usage
		PRIMARY KEY
		USING INDEX TABLESPACE &tab_space_index
		STORAGE (INITIAL 10k),
	RESERVATION_ID	NUMBER(8,0)	NOT NULL
        CONSTRAINT RESERVATION_USAGE_FK
        REFERENCES CHEMINFRA.RESERVATION(ID),
    PROJECT VARCHAR2(255),
    COMPOUND VARCHAR2(255),
    BATCH VARCHAR2(255),
    SAMPLE VARCHAR2(255)
	)
	TABLESPACE &TAB_SPACE_TABLE
    STORAGE (INITIAL 200K);
    
GRANT SELECT, INSERT, UPDATE, DELETE ON CHEMINFRA.RESERVATION_USAGE TO CHEMINFRAUSER;    
  
CREATE SEQUENCE CHEMINFRA.RESERVATION_USAGE_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
GRANT SELECT ON CHEMINFRA.RESERVATION_USAGE_SEQ to CHEMINFRAUSER;

--select CHEMINFRA.RESERVATION_USAGE_SEQ.nextval from dual;   
commit;  
