DEFINE tab_space_table=ACT0_TAB
DEFINE tab_space_index=ACT0_IDX

PROMPT Creating TABLE INSTRUMENT_DEPUTY
CREATE TABLE CHEMINFRA.INSTRUMENT_PRIORITY_USERS (
    ID NUMBER(8,0) NOT NULL
		CONSTRAINT pk_instrument_priority_users
		PRIMARY KEY
		USING INDEX TABLESPACE &tab_space_index
		STORAGE (INITIAL 10k),
	INSTRUMENT_ID	NUMBER(8,0)	NOT NULL
        CONSTRAINT fk_instrument_priority_user_id
        REFERENCES CHEMINFRA.INSTRUMENT(ID),
    PRIORITY_USER VARCHAR2(64)
	)
	TABLESPACE &TAB_SPACE_TABLE
    STORAGE (INITIAL 200K);
    
GRANT SELECT, INSERT, UPDATE, DELETE ON CHEMINFRA.INSTRUMENT_PRIORITY_USERS TO CHEMINFRAUSER;    
    
CREATE SEQUENCE CHEMINFRA.INSTRPRIORUSR_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
GRANT SELECT ON CHEMINFRA.INSTRPRIORUSR_SEQ to CHEMINFRAUSER;

CREATE TABLE CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE (
    ID NUMBER(8,0) NOT NULL
		CONSTRAINT pk_allowed_instrument_reservation_usage
		PRIMARY KEY
		USING INDEX TABLESPACE &tab_space_index
		STORAGE (INITIAL 10k),
	INSTRUMENT_ID	NUMBER(8,0)	NOT NULL
        CONSTRAINT fk_instrument_allowed_reservation_usage
        REFERENCES CHEMINFRA.INSTRUMENT(ID)
	)
	TABLESPACE &TAB_SPACE_TABLE
    STORAGE (INITIAL 200K);
    
GRANT SELECT, INSERT, UPDATE, DELETE ON CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE TO CHEMINFRAUSER;    
    
CREATE SEQUENCE CHEMINFRA.ALLOWINSTRRESAUSG_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
GRANT SELECT ON CHEMINFRA.ALLOWINSTRRESAUSG_SEQ to CHEMINFRAUSER;

Insert into CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE (ID,INSTRUMENT_ID) values (CHEMINFRA.ALLOWINSTRRESAUSG_SEQ.nextval,880);
Insert into CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE (ID,INSTRUMENT_ID) values (CHEMINFRA.ALLOWINSTRRESAUSG_SEQ.nextval,1341);
Insert into CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE (ID,INSTRUMENT_ID) values (CHEMINFRA.ALLOWINSTRRESAUSG_SEQ.nextval,1342);
Insert into CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE (ID,INSTRUMENT_ID) values (CHEMINFRA.ALLOWINSTRRESAUSG_SEQ.nextval,1160);
Insert into CHEMINFRA.ALLOWED_INSTRUMENT_RESERVATION_USAGE (ID,INSTRUMENT_ID) values (CHEMINFRA.ALLOWINSTRRESAUSG_SEQ.nextval,1231);

ALTER TABLE CHEMINFRA.INSTRUMENT ADD START_TIMEPOINT VARCHAR2(32) ;
ALTER TABLE CHEMINFRA.INSTRUMENT ADD MAX_DAYS NUMBER(8, 0);
ALTER TABLE CHEMINFRA.INSTRUMENT ADD HIGHLIGHT_COMMENT NUMBER(1, 0) DEFAULT(0);
UPDATE CHEMINFRA.INSTRUMENT SET HIGHLIGHT_COMMENT = 1 WHERE NAME = 'Tissue LyzerII Qiagen';

INSERT INTO cheminfra.instrument (id,name,description,status,location,reservable,username,groupname,infotitle,infomessage,ispublic,selectoverlap,ratiocomment,emailnotification,step_increment, start_timepoint, max_days) 
    VALUES 
    (cheminfra.instrument_seq.nextval,'Prep_LCMS_01','','Working','H91.O1.K13','1','MUELLECL','CHEMISTRY',NULL,NULL,'1','0',NULL,'0','0','14:00', 1);

--SELECT last_number FROM all_sequences WHERE sequence_owner = 'CHEMINFRA' and sequence_name = 'INSTRUMENT_SEQ';

INSERT INTO "CHEMINFRA"."GROUPINSTRUMENT" (IID, GID) VALUES (1561, '1');
INSERT INTO "CHEMINFRA"."GROUPINSTRUMENT" (IID, GID) VALUES (1561, '4');

INSERT INTO "CHEMINFRA"."INSTRUMENT_PRIORITY_USERS" (ID, INSTRUMENT_ID, PRIORITY_USER) VALUES (CHEMINFRA.INSTRPRIORUSR_SEQ.nextval, 1561, 'RICHARS');
INSERT INTO "CHEMINFRA"."INSTRUMENT_PRIORITY_USERS" (ID, INSTRUMENT_ID, PRIORITY_USER) VALUES (CHEMINFRA.INSTRPRIORUSR_SEQ.nextval, 1561, 'POPINCL1');
INSERT INTO "CHEMINFRA"."INSTRUMENT_PRIORITY_USERS" (ID, INSTRUMENT_ID, PRIORITY_USER) VALUES (CHEMINFRA.INSTRPRIORUSR_SEQ.nextval, 1561, 'RIBICV');
INSERT INTO "CHEMINFRA"."INSTRUMENT_PRIORITY_USERS" (ID, INSTRUMENT_ID, PRIORITY_USER) VALUES (CHEMINFRA.INSTRPRIORUSR_SEQ.nextval, 1561, 'SIEFKES');


Insert into CHEMINFRA.INSTRUMENT_DEPUTY (ID,INSTRUMENT_ID,DEPUTY) values (CHEMINFRA.INSTRDEPUTY_SEQ.nextval,1561,'BENMEKA1');

ALTER TABLE CHEMINFRA.RESERVATION_USAGE ADD SAMPLE_TYPE VARCHAR2(32) ;
ALTER TABLE CHEMINFRA.RESERVATION_USAGE ADD SPECIE VARCHAR2(32) ;

commit;