alter table CHEMINFRA.INSTRUMENT add STEP_INCREMENT NUMBER(3,0) DEFAULT 0;
update CHEMINFRA.INSTRUMENT set STEP_INCREMENT = 5 where SELECTOVERLAP = 1;

--TEST
SET DEFINE OFF;
Insert into CHEMINFRA.INSTRUMENT (ID,NAME,DESCRIPTION,STATUS,LOCATION,RESERVABLE,USERNAME,GROUPNAME,INFOTITLE,INFOMESSAGE,ISPUBLIC,SELECTOVERLAP,RATIOCOMMENT,EMAILNOTIFICATION) values (CHEMINFRA.INSTRUMENT_SEQ.nextval,'Ze K Machine','K2000','Working','H89.O5.E4.1',1,'BENMEKA1','PPG',null,null,1,0,' ',0);
commit;
--1501
Insert into CHEMINFRA.INSTRUMENT_DEPUTY (ID,INSTRUMENT_ID,DEPUTY) values (CHEMINFRA.INSTRDEPUTY_SEQ.nextval,1501,'MANKOKA1');

--Insert into CHEMINFRA.GROUPINSTRUMENT (IID,GID) values (1501,1);
--Insert into CHEMINFRA.GROUPINSTRUMENT (IID,GID) values (1501,4);
REM INSERTING into CHEMINFRA.RESOPTIONSLINK

Insert into CHEMINFRA.RESOPTIONSLINK (INSTID,OPTID) values (1501,1);
Insert into CHEMINFRA.RESOPTIONSLINK (INSTID,OPTID) values (1501,2);
Insert into CHEMINFRA.RESOPTIONSLINK (INSTID,OPTID) values (1501,3);
Insert into CHEMINFRA.RESOPTIONSLINK (INSTID,OPTID) values (1501,4);
Insert into CHEMINFRA.RESOPTIONSLINK (INSTID,OPTID) values (1501,5);
Insert into CHEMINFRA.RESOPTIONSLINK (INSTID,OPTID) values (1501,6);
commit;